language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '9'
git:
  depth: 3
script:
  - yarn build
  - echo 'cv.arepa.dev' > public/CNAME
deploy:
  name: Elmo@gremlim
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: master
  commit_message: "Elmo@gremlim - Deploy release ${TRAVIS_TAG}"
  fqdn: cv.arepa.dev
  on:
    branch: develop