language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '9'
git:
  depth: 3
script:
  - yarn build
  - echo 'robotum-game' > public/CNAME
deploy:
  name: sacha.nocetto@hotmail.com
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: master
  commit_message: "sacha.nocetto@hotmail.com - Deploy release ${TRAVIS_TAG}"
  fqdn: robotum-game
  on:
    branch: develop